<?php

/*
 * Million Dollar Script Two
 *
 * @author      Ryan Rhode
 * @copyright   (C) 2025, Ryan Rhode
 * @license     https://opensource.org/licenses/GPL-3.0 GNU General Public License, version 3
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 *
 *    Million Dollar Script
 *    Pixels to Profit: Ignite Your Revolution
 *    https://milliondollarscript.com/
 *
 */

namespace MillionDollarScript\Classes\Web;

use MillionDollarScript\Classes\System\Utility;
use MillionDollarScript\Classes\Data\Options;
use MillionDollarScript\Classes\System\Filesystem;

defined( 'ABSPATH' ) or exit;

/**
 * Output dynamic CSS styles for frontend and login pages.
 */
class Styles {

    private const DYNAMIC_CSS_FILENAME = 'dynamic-styles.css';

    /**
     * Get the absolute server path to the dynamic CSS file.
     *
     * @return string
     */
    public static function get_dynamic_css_filepath(): string {
        $upload_path = Utility::get_upload_path(); // e.g., /var/www/html/wp-content/uploads/milliondollarscript/
        return $upload_path . self::DYNAMIC_CSS_FILENAME;
    }

    /**
     * Get the URL to the dynamic CSS file.
     *
     * @return string
     */
    public static function get_dynamic_css_url(): string {
        $upload_dir = wp_upload_dir(); // Gets an array with 'baseurl', 'basedir', etc.
        // Ensure the baseurl does not have a trailing slash before appending our path and filename
        return rtrim( $upload_dir['baseurl'], '/' ) . '/milliondollarscript/' . self::DYNAMIC_CSS_FILENAME;
    }

    /**
     * Generate and save the dynamic CSS to a file.
     *
     * @return bool True on success, false on failure.
     */
    public static function save_dynamic_css_file(): bool {
        $css_content = self::get_dynamic_css();
        $warning_comment = "/*
 * WARNING: Do not edit this file directly.
 * This file is automatically generated and will be overwritten
 * when plugin options are saved.
 */
";
        $file_content = $warning_comment . $css_content;
        $filepath = self::get_dynamic_css_filepath();

        return Filesystem::put_contents( $filepath, $file_content );
    }

    /**
     * Generate dynamic CSS styles for MDS pages and login.
     * This method now directly returns the CSS string.
     *
     * @return string The generated CSS.
     */
    public static function get_dynamic_css(): string {
        // Fetch colors via Options::get_option with fallbacks
        $primary_color    = Options::get_option( 'primary_color', '#ff0000', true );
        $secondary_color  = Options::get_option( 'secondary_color', '#000000', true );
        $background_color = Options::get_option( 'background_color', '#ffffff', true );
        $text_color       = Options::get_option( 'text_color', '#333333', true );

        $button_color            = Options::get_option( 'button-color', '#0073aa', true );
        $button_text_color       = Options::get_option( 'button_text_color', '#ffffff', true );
        $button_secondary_bg     = Options::get_option( 'button_secondary_bg', '#91877D', true );
        $button_secondary_text   = Options::get_option( 'button_secondary_text_color', '#ffffff', true ); // Matched key from previous edit
        $button_tertiary_bg      = Options::get_option( 'button_tertiary_bg', '#F6F7F7', true );     // Matched key from previous edit
        $button_tertiary_text    = Options::get_option( 'button_tertiary_text_color', '#000000', true ); // Matched key from previous edit
        $button_border_radius    = Options::get_option( 'button_border_radius', '4', true );          // Matched key from previous edit

        $button_success_bg     = Options::get_option( 'button_success_bg', '#28a745', true );
        $button_success_text   = Options::get_option( 'button_success_text_color', '#ffffff', true ); // Assuming text color for success
        $button_danger_bg      = Options::get_option( 'button_danger_bg', '#f44336', true );
        $button_danger_text    = Options::get_option( 'button_danger_text_color', '#ffffff', true );   // Assuming text color for danger

        $error_color       = Options::get_option( 'error_color', '#dc3232', true );
        $success_color     = Options::get_option( 'success_color', '#46b450', true );
        $warning_color     = Options::get_option( 'warning_color', '#ffb900', true );
        $info_color        = Options::get_option( 'info_color', '#72aee6', true );
        $grid_link_color   = Options::get_option( 'grid_link_color', '#0073aa', true );
        $hover_color       = Options::get_option( 'hover_color', '#005177', true );
        $grid_border_color = Options::get_option( 'grid_border_color', '#dddddd', true );

        // Sanitize for CSS output (important when embedding directly, less so for CSS vars but good practice)
        // For CSS variables, the browser handles parsing, but it's still good to ensure they are valid color codes or values.
        // For simplicity, we'll assume Options::get_option handles basic sanitization or returns valid defaults.
        // If more complex sanitization (e.g. ensuring valid hex) is needed, it could be added here.

        $css = "
:root {
    --mds-primary-color: {$primary_color};
    --mds-secondary-color: {$secondary_color};
    --mds-background-color: {$background_color};
    --mds-text-color: {$text_color};

    --mds-button-color: {$button_color};
    --mds-button-text-color: {$button_text_color};
    --mds-button-secondary-bg: {$button_secondary_bg};
    --mds-button-secondary-text-color: {$button_secondary_text};
    --mds-button-tertiary-bg: {$button_tertiary_bg};
    --mds-button-tertiary-text-color: {$button_tertiary_text};
    --mds-button-border-radius: {$button_border_radius}px; /* Assuming px is desired for radius */

    --mds-button-success-bg: {$button_success_bg};
    --mds-button-success-text-color: {$button_success_text};
    --mds-button-danger-bg: {$button_danger_bg};
    --mds-button-danger-text-color: {$button_danger_text};

    --mds-error-color: {$error_color};
    --mds-success-color: {$success_color};
    --mds-warning-color: {$warning_color};
    --mds-info-color: {$info_color};

    --mds-grid-link-color: {$grid_link_color};
    --mds-hover-color: {$hover_color};
    --mds-grid-border-color: {$grid_border_color};
}

body, .mds-container, .mds-text-color {
    color: var(--mds-text-color);
}
body, .mds-container, .mds-body-bg-color {
    background-color: var(--mds-background-color);
}
.mds-primary-color { color: var(--mds-primary-color); }
.mds-primary-bg-color { background-color: var(--mds-primary-color); }
.mds-secondary-color { color: var(--mds-secondary-color); }
.mds-secondary-bg-color { background-color: var(--mds-secondary-color); }

/* Original typography and inputs from output_dynamic_styles */
.mds-container p,
.mds-container label {
    color: var(--mds-text-color);
}
.mds-container a {
    color: var(--mds-primary-color);
}
.mds-container input[type='text'],
.mds-container input[type='password'],
.mds-container select,
.mds-container textarea {
    background-color: var(--mds-background-color);
    border: 1px solid var(--mds-secondary-color);
    color: var(--mds-text-color);
}
.mds-container table th {
    background-color: var(--mds-secondary-color);
    color: var(--mds-button-text-color); /* Assuming header text is like button text */
}
.mds-container table td {
    /* background-color already handled by .mds-container bg */
    /* color already handled by .mds-container text */
}

/* Buttons using CSS Variables */
.mds-button, input[type='submit'].mds-button, button.mds-button {
    background-color: var(--mds-button-color);
    color: var(--mds-button-text-color);
    border-radius: var(--mds-button-border-radius);
    border: none; /* Consistent with original output */
}
.mds-button-secondary, input[type='submit'].mds-button-secondary, button.mds-button-secondary {
    background-color: var(--mds-button-secondary-bg);
    color: var(--mds-button-secondary-text-color);
    border-radius: var(--mds-button-border-radius);
    border: none;
}
.mds-button-tertiary, input[type='submit'].mds-button-tertiary, button.mds-button-tertiary {
    background-color: var(--mds-button-tertiary-bg);
    color: var(--mds-button-tertiary-text-color);
    border-radius: var(--mds-button-border-radius);
    border: none;
}

#loginform input[type=\"submit\"],
.mds-register-link,
.mds-container input[type='button'],
.mds-container input[type='submit'],
.mds-button, a.mds-button {
    /* Base button style, uses primary button vars */
    background-color: var(--mds-button-color);
    color: var(--mds-button-text-color);
    border-radius: var(--mds-button-border-radius);
    border: none;
}

.mds-button.mds-success,
.mds-container input[type='button'].mds-confirm,
.mds-container input[type='button'].mds-upload,
.mds-container input[type='button'].mds-write,
.mds-container input[type='button'].mds-pay,
.mds-container input[type='button'].mds-continue,
.mds-container input[type='submit'].mds-complete,
.mds-container #submit_button1, /* Specific ID from original */
.mds-container #submit_button2  /* Specific ID from original */
{
    background-color: var(--mds-button-success-bg);
    color: var(--mds-button-success-text-color);
}

.mds-button.mds-danger,
.mds-container #reset_button /* Specific ID from original */
{
    background-color: var(--mds-button-danger-bg);
    color: var(--mds-button-danger-text-color);
}

/* General hover effect for buttons, can be refined */
.mds-button:hover,
#loginform input[type=\"submit\"]:hover,
.mds-container input[type='button']:hover,
.mds-container input[type='submit']:hover,
a.mds-button:hover {
    filter: brightness(90%);
}

/* Alerts & Notices */
.mds-notice.mds-error, .mds-error-text { color: var(--mds-error-color); }
.mds-notice.mds-success, .mds-success-text { color: var(--mds-success-color); }
.mds-notice.mds-warning, .mds-warning-text { color: var(--mds-warning-color); }
.mds-notice.mds-info, .mds-info-text { color: var(--mds-info-color); }

/* Grid Specific */
.mds-pixel-grid a, .mds-grid-link-color { color: var(--mds-grid-link-color); }
.mds-pixel-grid a:hover, .mds-grid-link-color:hover { color: var(--mds-hover-color); }
.mds-pixel-grid, .mds-pixel-grid td, .mds-grid-border-color {
    border-color: var(--mds-grid-border-color);
}

		";

		// Allow filtering of the CSS
		$css = apply_filters( 'mds_dynamic_css', $css );

        return trim( $css );
    }

    /**
     * Enqueue dynamic CSS file after the core or login stylesheet.
     */
    public static function enqueue_dynamic_styles(): void {
        if ( is_admin() ) {
            return;
        }

        global $pagenow;
        $is_login_page = ( 'wp-login.php' === $pagenow );
        $is_mds_page = Utility::is_mds_page();

        if ( ! $is_login_page && ! $is_mds_page ) {
            return;
        }

        $css_filepath = self::get_dynamic_css_filepath();

        if ( ! Filesystem::file_exists( $css_filepath ) ) {
            // Attempt to generate it if it doesn't exist, as a fallback.
            // This is useful for initial activation or if the file was somehow deleted.
            if ( ! self::save_dynamic_css_file() ) {
                // Log error or notify admin if file can't be created/found
                return; // Can't enqueue if file doesn't exist and can't be created
            }
        }

        $handle = 'mds-dynamic-styles';
        $src = self::get_dynamic_css_url();
        $deps = $is_login_page ? [ 'login' ] : [ 'mds' ];
        $version = filemtime( $css_filepath );

        wp_enqueue_style( $handle, $src, $deps, $version );
    }
}